### ISSUE TITLE
Distinguish project from Data Harmonization

### ISSUE THREAD

**Issue by cgchute** [data2health/clinical-adaptor#15]
This Repo appears to have been introduced to correspond to the FDA data submission, using FHIR as a canonical model.  While related, I think this should be distinguished from the Clinical Harmonization (across CTSA hubs for federated query) problem.  Some of the text for this Repo was borrowed from harmonization.  Should we disambiguate this?

**Comment by jmcmurry** [comment]
I too was wondering whether this repo shouldn't be renamed to data-harmonization for exactly this reason. We can have specific milestones for each component of the project.

**Comment by cgchute** [comment]
There already is a data harmonization repos, of course.  So this is a little redundant.  I opted not to make a big deal, since I think the FDA submission issues are important to CTSA.  This is not the same, as the issues suggests.
Chris

**Comment by jmcmurry** [comment]
Per Ken's request, we're experimenting with making data-harmonization the parent, and clinical adaptor the child. Thus closing for now,
